# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        AppBundle\Entity\User: sha512

    providers:
        in_memory:
            memory:
                users:
                    zuzia:
                        password: $2a$04$5LldtUtbspJ4fQuRhQU92e5wRCb6Ns/3wh3g188de58vOav9Tz5LS
                        roles: 'ROLE_USER'
                    admin:
                        password: $2a$04$SOV6P1CRnJjMAyLIOnX9GuYj4NijEoC4HmcIEQ1A9NKM5x4byb3ym
                        roles: 'ROLE_ADMIN'

        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            security: false
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            http_basic: ~
            provider: our_db_provider

        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
