services:
    app.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\User
    app.project_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Project
    app.role_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Role
    app.board_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Board
    app.task_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Task

    app.user_type_form:
        class: AppBundle\Form\UserType
        tags:
            - { name: form.type, alias: user }
    app.project_type_form:
        class: AppBundle\Form\ProjectType
        tags:
            - { name: form.type, alias: project }
    app.role_type_form:
        class: AppBundle\Form\RoleType
        tags:
            - { name: form.type, alias: role }
    app.board_type_form:
        class: AppBundle\Form\BoardType
        tags:
            - { name: form.type, alias: role }
    app.task_type_form:
        class: AppBundle\Form\TaskType
        tags:
            - { name: form.type, alias: role }

    app.projects_controller:
        class: AppBundle\Controller\ProjectsController
        arguments:
          - @translator
          - @templating
          - @session
          - @router
          - @app.project_repository
          - @form.factory
          - @security.context

    app.projects_boards_controller:
        class: AppBundle\Controller\BoardsController
        arguments:
          - @translator
          - @templating
          - @session
          - @router
          - @app.board_repository
          - @app.project_repository
          - @form.factory
          - @security.context

    app.projects_tasks_controller:
        class: AppBundle\Controller\TasksController
        arguments:
          - @translator
          - @templating
          - @session
          - @router
          - @app.task_repository
          - @app.project_repository
          - @form.factory
          - @security.context

    app.dashboard_controller:
        class: AppBundle\Controller\DashboardController
        arguments:
            - @translator
            - @templating
            - @security.context

# Admin
    admin.admin_controller:
        class: AppBundle\Controller\Admin\AdminController
        arguments:
            - @translator
            - @templating
            - @router
            - @session
            - @doctrine.orm.entity_manager
            - @app.user_repository
            - @form.factory
            - @security.encoder_factory
            - @security.context
    admin.roles_controller:
        class: AppBundle\Controller\Admin\RolesController
        arguments:
          - @translator
          - @templating
          - @session
          - @router
          - @app.role_repository
          - @form.factory
    admin.projects_controller:
        class: AppBundle\Controller\Admin\ProjectsController
        arguments:
          - @translator
          - @templating
          - @session
          - @router
          - @app.project_repository
          - @form.factory
    admin.user_form:
        class: AppBundle\Form\Admin\UserType
        tags:
            - { name: form.type, alias: admin_user }
