services:
    app.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\User
    app.project_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Project

    app.user_type_form:
        class: AppBundle\Form\UserType
        tags:
            - { name: form.type, alias: user }
    app.project_type_form:
        class: AppBundle\Form\ProjectType
        tags:
            - { name: form.type, alias: project }

    app.projects_controller:
        class: AppBundle\Controller\ProjectsController
        arguments:
          - @translator
          - @templating
          - @session
          - @router
          - @app.project_repository
          - @form.factory

    admin.admin_controller:
        class: AppBundle\Controller\Admin\AdminController
        arguments:
            - @translator
            - @templating
            - @router
            - @doctrine.orm.entity_manager
            - @security.context
            - @app.user_repository
